### ISSUE TITLE
[Serial] Terminal hits error and stays in broken state until refresh

### ISSUE THREAD

**Issue by microbit-matt-hillsdon** [microbit-foundation/python-editor-next#677]
Giles got into a state where he could not interact with the REPL or see serial output.

This persisted until we refreshed the tab regardless of disconnect/reconnect/flash.

I think it's represented by [this Sentry issue](https://sentry.io/organizations/microbit/issues/3190440968/?project=5677402&query=is%3Aunresolved). There's a similar one with working source map [here](https://sentry.io/organizations/microbit/issues/3176991175/?project=5677402&query=is%3Aunresolved+_forEachCell&statsPeriod=14d).

**Comment by microbit-matt-hillsdon** [comment]
This is the same as https://github.com/microbit-foundation/python-editor-next/issues/603. I also saw it on a call with Jonny earlier today.

Logs from #603:

```
instrument.ts:125 Device status CONNECTED
helpers.ts:120 Uncaught TypeError: Cannot read properties of undefined (reading 'loadCell')
    at t._forEachCell (xterm.js:1:122707)
    at t._drawBackground (xterm.js:1:123185)
    at t.onGridChanged (xterm.js:1:124882)
    at t.renderRows (xterm.js:1:116358)
    at t._renderRows (xterm.js:1:162731)
    at e._renderCallback (xterm.js:1:160756)
    at e._innerRefresh (xterm.js:1:36928)
    at xterm.js:1:36644
    at i (helpers.ts:98:17)
instrument.ts:125 Stopping serial before flash
```

**Comment by microbit-matt-hillsdon** [comment]
You get the same trace if you open() a terminal twice, with or without an intervening dispose.

I think XTerm.js is being remounted (reason TBC). It does the open call but not clean-up as there's a weird split of responsibilities between the hook and the component. It's like that to support the serial actions having access to the terminal.

A related bug can be triggered by changing language after connect. That results in the terminal being disposed but not recreated (triggered by the value of intl changing).

I think we should change the design so that the context tracks the current terminal (probably via a ref) which is used for the actions and all the lifecycle management moves into the XTerm component.
