### ISSUE TITLE
[Simulator] Fix key for modules

### ISSUE THREAD

**Issue by microbit-matt-hillsdon** [microbit-foundation/python-editor-next#878]
```
react_devtools_backend.js:4026 Warning: Each child in a list should have a unique "key" prop.

Check the render method of `SimulatorModules`. See https://reactjs.org/link/warning-keys for more information.
    at http://localhost:3000/static/js/bundle.js:80857:24
    at SimulatorModules (http://localhost:3000/static/js/bundle.js:32588:84)
    at div
    at http://localhost:3000/static/js/bundle.js:165999:66
    at http://localhost:3000/static/js/bundle.js:80857:24
    at VStack
```

**Comment by microbit-robert** [comment]
Closed by #886.
