### ISSUE TITLE
[Simulator] Calling reset() in MicroPython program asserts in sim

### ISSUE THREAD

**Issue by microbit-matt-hillsdon** [microbit-foundation/python-editor-next#899]
Running

```
from microbit import *

reset()
```

in the sim results in the following logged error:

```
Uncaught (in promise) Error: Already started!
    at WebAssemblyOperations.start (micropython.js:306:15)
    at BoardUI.start (micropython.js:1783:23)
    at BoardUI.reset (micropython.js:1793:12)
```

There are likely other negative consequences.

**Comment by microbit-matt-hillsdon** [comment]
Recent changes mean this now restarts OK. In the demo it seems to work fine. But in the editor we see serial no longer echos what you type (and perhaps is otherwise broken).

However, it works fine with this program:

```
n = 0
while True:
    n += 1
    print(n)
    sleep(1000)
```

**Comment by microbit-matt-hillsdon** [comment]
OK, so this does actually work but it's a little confusing as there's time/opportunity for the sim to print the next REPL prompt.
That made me think serial should be working even though it was actually just busy running the program.
I think the reset HAL method should throw similarly to the panic case. Then we can handle it in the same way but just restart.

**Comment by microbit-matt-hillsdon** [comment]
Sim PR that takes the ResetError approach:

https://github.com/microbit-foundation/micropython-microbit-v2-simulator/pull/54

**Comment by microbit-matt-hillsdon** [comment]
Sim PR merged. Closing.
