### ISSUE TITLE
Korean translation issue with delete-file-action

### ISSUE THREAD

**Issue by microbit-matt-hillsdon** [microbit-foundation/python-editor-next#956]
![image](https://user-images.githubusercontent.com/44397098/189927814-6ae219bd-9d08-4fc4-bb88-2d473bfcd006.png)

When running locally you get a useful logged error that we don't get in review deployments. I'll check all other languages locally too.

```
utils.js:19 Error: [@formatjs/intl Error FORMAT_ERROR] Error formatting message: "delete-file-action", using id as fallback. 
Locale: ko
MessageID: delete-file-action
Default Message: undefined
Description: undefined 
 

The intl string context variable "filename" was not provided to the string "undefined"
Error: The intl string context variable "filename" was not provided to the string "undefined"
    at MissingValueError.FormatError [as constructor] (error.js:14:1)
    at new MissingValueError (error.js:44:1)
    at formatToParts (formatters.js:66:1)
    at IntlMessageFormat.formatToParts (core.js:117:1)
    at IntlMessageFormat.format (core.js:95:1)
    at formatMessage (message.js:79:1)
    at formatMessage (provider.js:44:1)
    at FormattedMessage (message.js:21:1)
    at renderWithHooks (react-dom.development.js:14985:1)
    at mountIndeterminateComponent (react-dom.development.js:17811:1)
    at new MessageFormatError (error.js:50:1)
    at formatMessage (message.js:82:1)
    at formatMessage (provider.js:44:1)
    at FormattedMessage (message.js:21:1)
```

**Comment by microbit-matt-hillsdon** [comment]
> Same string has an issue in zh-CN.

No, it doesn't, this is just a very confusing message from formatjs when switching from ko to zh-CN.

**Comment by microbit-matt-hillsdon** [comment]
Fixed the string in Crowdin: https://crowdin.com/translate/microbitorg/6426/en-ko#331470

I'll re-do the translation sync and discuss further string QA elsewhere.
